// <auto-generated />
using Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = 123457,
                            Category = "Technology",
                            Description = "Looking for IT consulting services.",
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "9876543210",
                            Price = 1200m,
                            Status = 0,
                            Suburb = "Melbourne"
                        },
                        new
                        {
                            Id = 123458,
                            Category = "Education",
                            Description = "Interested in online learning platforms.",
                            Email = "michael.johnson@example.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            PhoneNumber = "4567891230",
                            Price = 800m,
                            Status = 0,
                            Suburb = "Brisbane"
                        },
                        new
                        {
                            Id = 123459,
                            Category = "Healthcare",
                            Description = "Seeking health insurance options.",
                            Email = "emily.davis@example.com",
                            FirstName = "Emily",
                            LastName = "Davis",
                            PhoneNumber = "1230984567",
                            Price = 500m,
                            Status = 0,
                            Suburb = "Perth"
                        },
                        new
                        {
                            Id = 123460,
                            Category = "Finance",
                            Description = "Looking for investment opportunities.",
                            Email = "chris.brown@example.com",
                            FirstName = "Chris",
                            LastName = "Brown",
                            PhoneNumber = "3216549870",
                            Price = 1500m,
                            Status = 0,
                            Suburb = "Adelaide"
                        },
                        new
                        {
                            Id = 123461,
                            Category = "Real Estate",
                            Description = "Searching for commercial properties.",
                            Email = "sarah.wilson@example.com",
                            FirstName = "Sarah",
                            LastName = "Wilson",
                            PhoneNumber = "6543217890",
                            Price = 2000m,
                            Status = 0,
                            Suburb = "Canberra"
                        },
                        new
                        {
                            Id = 123462,
                            Category = "Travel",
                            Description = "Planning a vacation package.",
                            Email = "david.martinez@example.com",
                            FirstName = "David",
                            LastName = "Martinez",
                            PhoneNumber = "7890123456",
                            Price = 700m,
                            Status = 0,
                            Suburb = "Gold Coast"
                        },
                        new
                        {
                            Id = 123463,
                            Category = "Food & Beverage",
                            Description = "Looking for catering services.",
                            Email = "laura.garcia@example.com",
                            FirstName = "Laura",
                            LastName = "Garcia",
                            PhoneNumber = "8901234567",
                            Price = 300m,
                            Status = 0,
                            Suburb = "Hobart"
                        },
                        new
                        {
                            Id = 123464,
                            Category = "Construction",
                            Description = "Interested in home renovation.",
                            Email = "james.anderson@example.com",
                            FirstName = "James",
                            LastName = "Anderson",
                            PhoneNumber = "5678901234",
                            Price = 2500m,
                            Status = 0,
                            Suburb = "Darwin"
                        },
                        new
                        {
                            Id = 123465,
                            Category = "Retail",
                            Description = "Looking for wholesale suppliers.",
                            Email = "sophia.lee@example.com",
                            FirstName = "Sophia",
                            LastName = "Lee",
                            PhoneNumber = "4321098765",
                            Price = 1000m,
                            Status = 0,
                            Suburb = "Newcastle"
                        },
                        new
                        {
                            Id = 123466,
                            Category = "Automotive",
                            Description = "Interested in buying a new car.",
                            Email = "daniel.taylor@example.com",
                            FirstName = "Daniel",
                            LastName = "Taylor",
                            PhoneNumber = "6789012345",
                            Price = 30000m,
                            Status = 0,
                            Suburb = "Geelong"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
